/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_financiera;

/**
 *
 * @author emili
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        textResultado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        rbtnNominal = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JToggleButton();
        btnInteres = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNper2 = new javax.swing.JTextField();
        textNper = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboxCalculo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtI2 = new javax.swing.JTextField();
        rbtnEfectiva = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        textVF = new javax.swing.JTextField();
        textVA = new javax.swing.JTextField();
        textI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        textVF1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        calculo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        textVA1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textNper1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textI1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        textResultado1 = new javax.swing.JTextField();
        btnRegresar1 = new javax.swing.JToggleButton();
        btnBorrar = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textResultado.setEditable(false);
        jPanel2.add(textResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 160, -1));

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        rbtnNominal.setText("Tasa Nominal");
        rbtnNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNominalActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        btnInteres.setText("Tasa Equvalente");
        btnInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresActionPerformed(evt);
            }
        });
        jPanel2.add(btnInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 106, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Interes Compuesto");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));
        jPanel2.add(txtNper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, -1));

        textNper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNperActionPerformed(evt);
            }
        });
        jPanel2.add(textNper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 108, -1));

        jLabel2.setText("Elija una opcion de calculo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setText("Tasa Nominal (j):");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel5.setText("Tasa de Interes (i):");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        comboxCalculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interes Compuesto (VA)", "Interes Compuesto (VF)", "Interes Compuesto(n)", "Interes Compuesto (i)", " " }));
        comboxCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCalculoActionPerformed(evt);
            }
        });
        jPanel2.add(comboxCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setText("Valor Futuro (VF):");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jPanel2.add(txtI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 120, -1));

        rbtnEfectiva.setText("Tasa Efectiva");
        rbtnEfectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEfectivaActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnEfectiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setText("Valor Actual (VA):");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel2.add(textVF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, -1));

        textVA.setEnabled(false);
        jPanel2.add(textVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, -1));

        textI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIActionPerformed(evt);
            }
        });
        jPanel2.add(textI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 86, -1));

        jLabel7.setText("Periodo de Capitalizacion (m):");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel4.setText("Periodo (n):");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel9.setText("Valor Futuro (VF):");

        textVF1.setEnabled(false);

        jLabel10.setText("Elija una opcion de calculo:");

        calculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interes Simple", "Interes Simple (VA)", "Interes Simple (VF)", "Interes Simple (n)", "Interes Simple (i)", " " }));
        calculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculoActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor Actual (VA):");

        jLabel12.setText("Periodo (n):");

        textNper1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNper1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Tasa de Interes (i):");

        textI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textI1ActionPerformed(evt);
            }
        });

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        textResultado1.setEditable(false);

        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel14.setText("Interes Simple");

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textVA1)
                    .addComponent(textNper1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textI1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(textVF1)
                    .addComponent(calculo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBorrar)
                            .addComponent(btnRegresar1))
                        .addContainerGap(105, Short.MAX_VALUE))))
            .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog3Layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(jLabel14)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(textResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNper1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textVF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar1))
                .addGap(33, 33, 33))
            .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog3Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel14)
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fiananzas.png"))); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Interes simple");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Interes compuesto");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(this.comboxCalculo.getSelectedIndex()){
            case 0:
            double va = 0;
            if(this.rbtnEfectiva.isSelected()){
                va = Double.parseDouble(this.textVF.getText())/Math.pow((1+Double.parseDouble(this.textI.getText())),Double.parseDouble(this.textNper.getText()));
            }
            if(this.rbtnNominal.isSelected()){
                va = Double.parseDouble(this.textVF.getText())/Math.pow((1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText()))),Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText()));
            }
            this.textResultado.setText(String.format("%.2f",va));
            break;
            case 1:
            double vf = 0;
            if(this.rbtnEfectiva.isSelected()){
                vf = Double.parseDouble(this.textVA.getText())*Math.pow((1+Double.parseDouble(this.textI.getText())),Double.parseDouble(this.textNper.getText()));
            }
            if(this.rbtnNominal.isSelected()){
                vf = Double.parseDouble(this.textVA.getText())*Math.pow((1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText()))),Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText()));
            }
            this.textResultado.setText(String.format("%.2f",vf));
            break;
            case 2:
            double nper = 0;
            if(this.rbtnEfectiva.isSelected()){
                nper = Math.log(Double.parseDouble(this.textVF.getText())/Double.parseDouble(this.textVA.getText()))/Math.log(1+Double.parseDouble(this.textI.getText()));
            }
            if(this.rbtnNominal.isSelected()){
                nper = Math.log(Double.parseDouble(this.textVF.getText())/Double.parseDouble(this.textVA.getText()))/(Double.parseDouble(this.txtNper2.getText())*Math.log(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText()))));
            }
            this.textResultado.setText(String.format("%.2f",nper));
            break;
            case 3:
            double i = 0;
            if(this.rbtnEfectiva.isSelected()){
                i = Math.pow((Double.parseDouble(this.textVF.getText())/Double.parseDouble(this.textVA.getText())), (1/Double.parseDouble(this.textNper.getText())))-1;
            }
            if(this.rbtnNominal.isSelected()){
                i = Double.parseDouble(this.txtNper2.getText())*(Math.pow((Double.parseDouble(this.textVF.getText())/Double.parseDouble(this.textVA.getText())), (1/(Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText()))))-1);
            }
            this.textResultado.setText(String.format("%.2f",i));
            break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textNperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNperActionPerformed

    private void rbtnEfectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEfectivaActionPerformed
        this.rbtnNominal.setSelected(false);
    }//GEN-LAST:event_rbtnEfectivaActionPerformed

    private void rbtnNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNominalActionPerformed
        this.rbtnEfectiva.setSelected(false);
    }//GEN-LAST:event_rbtnNominalActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       /* VentanaPrincipal vPrincipal = new VentanaPrincipal();
        vPrincipal.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboxCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCalculoActionPerformed
        switch(this.comboxCalculo.getSelectedIndex()){
            case 0:
            this.textVF.setEnabled(true);
            this.textVA.setEnabled(false);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(true);
                this.textNper.setEnabled(true);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(true);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(true);
            }
            break;
            case 1:
            this.textVF.setEnabled(false);
            this.textVA.setEnabled(true);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(true);
                this.textNper.setEnabled(true);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(true);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(true);
            }
            break;
            case 2:
            this.textVF.setEnabled(true);
            this.textVA.setEnabled(true);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(true);
                this.textNper.setEnabled(false);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(true);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(false);
            }
            break;
            case 3:
            this.textVF.setEnabled(true);
            this.textVA.setEnabled(true);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(false);
                this.textNper.setEnabled(true);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(true);
            }
            break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCalculoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.textI.setText("");
        this.textNper.setText("");
        this.textResultado.setText("");
        this.textVA.setText("");
        this.textVF.setText("");
        this.txtI2.setText("");
        this.txtNper2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresActionPerformed
     /*   VentanaTasa tasa = new VentanaTasa();
        tasa.setVisible(true);*/
    }//GEN-LAST:event_btnInteresActionPerformed

    private void calculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculoActionPerformed
        switch(this.calculo.getSelectedIndex()){
            case 0:
            this.textVF.setEnabled(false);
            this.textVA.setEnabled(true);
            this.textI.setEnabled(true);
            this.textNper.setEnabled(true);
            break;
            case 1:
            this.textVF.setEnabled(true);
            this.textVA.setEnabled(false);
            this.textI.setEnabled(true);
            this.textNper.setEnabled(true);
            break;
            case 2:
            this.textVF.setEnabled(false);
            this.textVA.setEnabled(true);
            this.textI.setEnabled(true);
            this.textNper.setEnabled(true);
            break;
            case 3:
            this.textVF.setEnabled(true);
            this.textVA.setEnabled(true);
            this.textI.setEnabled(true);
            this.textNper.setEnabled(false);
            break;
            case 4:
            this.textVF.setEnabled(true);
            this.textVA.setEnabled(true);
            this.textI.setEnabled(false);
            this.textNper.setEnabled(true);
            break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_calculoActionPerformed

    private void textNper1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNper1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNper1ActionPerformed

    private void textI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textI1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        switch(this.calculo.getSelectedIndex()){
            case 0:
            double intSimple = 0;
            intSimple = Double.parseDouble(this.textVA.getText())*Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.textI.getText());
            this.textResultado.setText(String.format("%.2f",intSimple));
            break;
            case 1:
            double va = 0;
            va = Double.parseDouble(this.textVF.getText())/(1+(Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.textI.getText())));
            this.textResultado.setText(String.format("%.2f",va));
            break;
            case 2:
            double vf = 0;
            vf = Double.parseDouble(this.textVA.getText())*(1+(Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.textI.getText())));
            this.textResultado.setText(String.format("%.2f",vf));
            break;
            case 3:
            double nper = 0;
            nper = ((Double.parseDouble(this.textVF.getText())/Double.parseDouble(this.textVA.getText()))-1)/Double.parseDouble(this.textI.getText());
            this.textResultado.setText(String.format("%.2f",nper));
            break;
            case 4:
            double i = 0;
            i = ((Double.parseDouble(this.textVF.getText())/Double.parseDouble(this.textVA.getText()))-1)/Double.parseDouble(this.textNper.getText());
            this.textResultado.setText(String.format("%.2f",i));
            break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        /*VentanaPrincipal vPrincipal = new VentanaPrincipal();
        vPrincipal.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.textI.setText("");
        this.textNper.setText("");
        this.textResultado.setText("");
        this.textVA.setText("");
        this.textVF.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
        
       
        
        
        
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBorrar;
    private javax.swing.JButton btnInteres;
    private javax.swing.JToggleButton btnRegresar;
    private javax.swing.JToggleButton btnRegresar1;
    private javax.swing.JComboBox<String> calculo;
    private javax.swing.JComboBox<String> comboxCalculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtnEfectiva;
    private javax.swing.JRadioButton rbtnNominal;
    private javax.swing.JTextField textI;
    private javax.swing.JTextField textI1;
    private javax.swing.JTextField textNper;
    private javax.swing.JTextField textNper1;
    private javax.swing.JTextField textResultado;
    private javax.swing.JTextField textResultado1;
    private javax.swing.JTextField textVA;
    private javax.swing.JTextField textVA1;
    private javax.swing.JTextField textVF;
    private javax.swing.JTextField textVF1;
    private javax.swing.JTextField txtI2;
    private javax.swing.JTextField txtNper2;
    // End of variables declaration//GEN-END:variables
}
